before_script: cp config/database.yml.example config/database.yml && bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rake db:test:prepare
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
